services:
  # Service PHP-FPM pour Symfony
  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    container_name: elliteam_php
    volumes:
      - .:/var/www/html:cached
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    working_dir: /var/www/html
    environment:
      APP_ENV: ${APP_ENV:-dev}
      DATABASE_URL: mysql://elliteam:elliteam@mysql:3306/elliteam?serverVersion=8.0
    networks:
      - elliteam
    depends_on:
      - mysql
      - mailhog

  # Serveur Web Nginx
  nginx:
    image: nginx:1.25-alpine
    container_name: symfony_nginx
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - elliteam
    depends_on:
      - php

  # Base de donn√©es MySQL
  mysql:
    image: mysql:8.0
    container_name: elliteam_mysql
    environment:
      MYSQL_ROOT_PASSWORD: Cibaco2024!
      MYSQL_DATABASE: elliteam
      MYSQL_USER: elliteam
      MYSQL_PASSWORD: elliteam
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - elliteam

  # PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: elliteam_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: Cibaco2024!
    ports:
      - "8081:80"
    networks:
      - elliteam
    depends_on:
      - mysql

  # mailhog
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1080:8025"
      - "1025:1025"
    networks:
      - elliteam

networks:
  elliteam:
    driver: bridge

volumes:
  mysql_data:
