
services:
  # Service PHP-FPM avec Symfony
  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    container_name: elliteam_php
    volumes:
      - ./:/var/www/symfony:cached
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - .:/var/www/html
    working_dir: /var/www/html
    environment:
      - APP_ENV=${APP_ENV:-dev}
      - DATABASE_URL="mysql://elliteam:elliteam@mysql:3306/elliteam?serverVersion=8.0"
    networks:
      - elliteam
    depends_on:
      - mysql

  # Serveur Web Nginx
  nginx:
    image: nginx:1.25-alpine
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/symfony:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - elliteam
    depends_on:
      - php

  # Base de données MySQL
  mysql:
    image: mysql:8.0
    container_name: elliteam_mysql
    environment:
        MYSQL_ROOT_PASSWORD: Cibaco2024!
        MYSQL_DATABASE: elliteam
        MYSQL_USER: elliteam
        MYSQL_PASSWORD: elliteam
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - elliteam

  # PhpMyAdmin (optionnel)
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: elliteam_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: Cibaco2024!
    ports:
      - "8081:80"
    networks:
      - elliteam
    depends_on:
      - mysql

  # MailDev pour tester les emails en développement
  maildev:
    image: maildev/maildev
    container_name: symfony_maildev
    ports:
      - "1080:1080"  # Interface web
      - "1025:1025"  # SMTP
    networks:
      - elliteam

  # Redis (optionnel - pour le cache)
  redis:
    image: redis:7-alpine
    container_name: elliteam_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - elliteam

networks:
  elliteam:
    driver: bridge

volumes:
  mysql_data:
  redis_data: