services:
  # Service PHP-FPM pour Symfony
  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    container_name: elliteam_php
    volumes:
      - .:/var/www/html:cached
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    working_dir: /var/www/html
    environment:
      APP_ENV: ${APP_ENV:-dev}
    networks:
      - elliteam
    depends_on:
      - mailhog

  # Serveur Web Nginx
  nginx:
    image: nginx:1.25-alpine
    container_name: symfony_nginx
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - elliteam
    depends_on:
      - php

  # mailhog
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1080:8025"
      - "1025:1025"
    networks:
      - elliteam

networks:
  elliteam:
    driver: bridge
